'use client';

import { Box, Card, CardContent, Typography, Button, Stack, Grid, MenuItem, TextField, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
import { Download, Print, FilterList } from '@mui/icons-material';

const reportTypes = [
    'Transaction Summary',
    'Customer Onboarding',
    'Loan Disbursement',
    'Deposit Statistics',
    'Revenue & Fees',
    'Audit Logs'
];

export default function ReportsPage() {
    return (
        <Stack spacing={3}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Box>
                    <Typography variant="h5" color="primary" fontWeight="bold">Analytics & Reports</Typography>
                    <Typography variant="body2" color="text.secondary">Generate and download official bank statements and reports</Typography>
                </Box>
                <Stack direction="row" spacing={1}>
                    <Button variant="outlined" startIcon={<Print />}>Print All</Button>
                    <Button variant="contained" startIcon={<Download />}>Bulk Export</Button>
                </Stack>
            </Box>

            <Paper sx={{ p: 2 }}>
                <Grid container spacing={2} alignItems="center">
                    <Grid size={{ xs: 12, md: 3 }}>
                        <TextField select fullWidth label="Report Type" size="small" defaultValue={reportTypes[0]}>
                            {reportTypes.map((type) => (
                                <MenuItem key={type} value={type}>{type}</MenuItem>
                            ))}
                        </TextField>
                    </Grid>
                    <Grid size={{ xs: 12, md: 2 }}>
                        <TextField type="date" fullWidth label="From Date" size="small" InputLabelProps={{ shrink: true }} />
                    </Grid>
                    <Grid size={{ xs: 12, md: 2 }}>
                        <TextField type="date" fullWidth label="To Date" size="small" InputLabelProps={{ shrink: true }} />
                    </Grid>
                    <Grid size={{ xs: 12, md: 2 }}>
                        <Button variant="contained" fullWidth startIcon={<FilterList />}>Generate</Button>
                    </Grid>
                </Grid>
            </Paper>

            <Box sx={{ display: 'grid', gridTemplateColumns: { md: '1fr 1fr' }, gap: 3 }}>
                <Card sx={{ borderLeft: '4px solid', borderColor: 'primary.main' }}>
                    <CardContent>
                        <Typography variant="subtitle2" color="text.secondary">Total Transaction Volume</Typography>
                        <Typography variant="h4" fontWeight="bold">₹ 12,45,67,890</Typography>
                        <Typography variant="caption" color="success.main">+12.5% vs Last Quarter</Typography>
                    </CardContent>
                </Card>
                <Card sx={{ borderLeft: '4px solid', borderColor: 'secondary.main' }}>
                    <CardContent>
                        <Typography variant="subtitle2" color="text.secondary">New Customers (This Month)</Typography>
                        <Typography variant="h4" fontWeight="bold">452</Typography>
                        <Typography variant="caption" color="success.main">+5.2% vs Last Month</Typography>
                    </CardContent>
                </Card>
            </Box>

            <TableContainer component={Paper}>
                <Box sx={{ p: 2, borderBottom: '1px solid #eee' }}>
                    <Typography variant="subtitle1" fontWeight="bold">Generated Reports List</Typography>
                </Box>
                <Table size="small">
                    <TableHead>
                        <TableRow>
                            <TableCell>Report Name</TableCell>
                            <TableCell>Period</TableCell>
                            <TableCell>Generated On</TableCell>
                            <TableCell>Generated By</TableCell>
                            <TableCell align="right">Actions</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {[1, 2, 3].map((i) => (
                            <TableRow key={i}>
                                <TableCell sx={{ fontWeight: 600 }}>{reportTypes[i % reportTypes.length]}</TableCell>
                                <TableCell>01-Jan-2026 to 31-Jan-2026</TableCell>
                                <TableCell>30-Jan-2026 14:20</TableCell>
                                <TableCell>Super Admin</TableCell>
                                <TableCell align="right">
                                    <Button size="small" startIcon={<Download />}>Download PDF</Button>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>
        </Stack>
    );
}
